spring:
  data:
    mongodb:
      host: 182.61.23.125
      database: noteshare
      username: admin
      password: admin
      authentication-database: admin

  redis:
    host: 182.61.23.125
    port: 6379
    password: 969023014

  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 465
    username: 1452618379@qq.com
    password: pakirsbjawwnbaaf
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    from: notehub官方
  elasticsearch:
    rest:
      username: elastic
      uris: http://139.9.217.28:9200
      password: 969023014


management:
  endpoints:
    web:
      exposure:
        include: '*'

qiniu:
  accessKey: "SStPJbNpriAFEzb0LvB1ooO7X__CB5xpwt8cE8UE"
  secretKey: "aMbK1T32B4_Gidwm_zbFAVPmaBG2j-DgZkEQLEmT"
  bucket: "notehub"



server:
  port: 9000
  servlet:
    context-path: /notehub
