spring:
  data:
    mongodb:
      host: 182.61.23.125
      database: noteshare
      username: admin
      password: admin
      authentication-database: admin

  redis:
    host: 182.61.23.125
    port: 6379
    password: 969023014

